#!/usr/bin/perl

#use strict;
use Getopt::Long;
use Data::Dumper;
use Cwd;

my $pwd = cwd;
print $pwd."\n";

my $path = 'c:';
my %dir_list;

sub read_directory($);
sub list_files(\%);

list_directory($path);
#print Dumper %dir_list;  

list_files(%dir_list);

foreach my $x (sort keys %dir_list)
{
 print "\n Directory $x contains $dir_list{$x} files. ";
}

sub list_directory($)
{
   my $dir = shift; 
   if(! $dir)
   {
        $dir = cwd ;
   } 
   
   opendir DD, $dir or die "Cannot open the directory: $!";  
   while($_ = readdir(DD))
    {
      next if  ($_ eq "." or $_ eq "..");
      if ( -d $_ && $_ =~  /^(1\d{3})/)
	 {
	     #print "\n Directory exists $_ in $dir \n";
	     $dir_list{$_} = 0 ; 
	 }
    }      
 close DD;
}

sub list_files(\%)
{
    my $dirs = shift;
 #   print Dumper $dirs;
    my $count = 0 ; 

     foreach my $dir (sort keys %{$dirs})
    {
	print " \n Directory =  $dir ";
        opendir DD, $dir or die "Cannot open the directory: $!";  
        while($_ = readdir(DD))
        	{
		    next if  ($_ eq "." or $_ eq "..");
		    print "\n \t $_ \t";
		    #$\="\t";	
		    print -s _ if -r _ and -f _ ;
	            $count ++;
		}
         $dirs->{$dir}=$count;
	 $count =0;   
         close DD;
    }
 }
 
  

